# Generated by Django 5.0.2 on 2024-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sponsor_types', models.CharField(max_length=200)),
                ('bidding_date', models.DateField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='event_posters/')),
            ],
        ),
    ]
