# Generated by Django 5.0.2 on 2024-02-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0002_remove_event_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bidding_date',
            new_name='biddingdate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='eventdate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name',
            new_name='organizername',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_phone',
            new_name='organizerphone',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sponsor_types',
            new_name='sponsortypes',
        ),
    ]
