# Generated by Django 5.0.2 on 2024-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0003_rename_bidding_date_event_biddingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsortypes',
            field=models.JSONField(),
        ),
    ]
