# Generated by Django 5.0.2 on 2024-02-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0004_alter_event_sponsortypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='biddingdate',
            new_name='BiddingDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventdate',
            new_name='EventDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='email',
            new_name='LeadOrganizerEmail',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizername',
            new_name='LeadOrganizerName',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizerphone',
            new_name='LeadOrganizerPhone',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sponsortypes',
            new_name='SponsorTypes',
        ),
    ]
