# Generated by Django 5.0.2 on 2024-02-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0005_rename_biddingdate_event_biddingdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='SponsorTypes',
        ),
    ]
