# Generated by Django 5.0.3 on 2024-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0007_event_eventname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('CoursePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CourseDuration', models.CharField(max_length=100)),
                ('TeacherName', models.CharField(max_length=100)),
                ('course_files', models.FileField(null=True, upload_to='course_materials/')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('LastUpdated', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
