# Generated by Django 5.0.3 on 2024-03-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0008_course_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
