# Generated by Django 5.0.3 on 2024-03-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0008_course_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_files',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
    ]
