# Generated by Django 5.0.3 on 2024-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0009_remove_course_course_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_files',
            field=models.FileField(null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
