# Generated by Django 5.0.3 on 2024-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0010_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_files',
            field=models.FileField(null=True, upload_to='course_materials/'),
        ),
    ]
