# Generated by Django 5.0.2 on 2024-02-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_delete_userprofile'),
        ('users_app', '0002_remove_userprofile_email_remove_userprofile_mobile_and_more'),
    ]

    operations = [
    ]
