# Generated by Django 5.0.3 on 2024-03-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_course_course_files_course_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_files',
        ),
    ]
