# Generated by Django 5.0.3 on 2024-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0003_remove_course_course_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_photo/'),
        ),
    ]
