# Generated by Django 5.0.2 on 2024-02-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
                ('BrandType', models.CharField(max_length=100)),
                ('SponserPhone', models.CharField(max_length=15)),
                ('SponserEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
