# Generated by Django 5.0.2 on 2024-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activesponsor',
            old_name='SponserEmail',
            new_name='SponsorEmail',
        ),
        migrations.RenameField(
            model_name='activesponsor',
            old_name='SponserPhone',
            new_name='SponsorPhone',
        ),
    ]
